# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.your_secret_key_field = QtWidgets.QLineEdit(self.centralwidget)
        self.your_secret_key_field.setGeometry(QtCore.QRect(20, 50, 201, 22))
        self.your_secret_key_field.setObjectName("your_api_field")
        self.user_api_field = QtWidgets.QLineEdit(self.centralwidget)
        self.user_api_field.setGeometry(QtCore.QRect(260, 50, 231, 22))
        self.user_api_field.setObjectName("reciever_api_field")
        self.your_api_label = QtWidgets.QLabel(self.centralwidget)
        self.your_api_label.setGeometry(QtCore.QRect(100, 30, 49, 16))
        self.your_api_label.setObjectName("your_api_label")
        self.reciever_api_label = QtWidgets.QLabel(self.centralwidget)
        self.reciever_api_label.setGeometry(QtCore.QRect(340, 30, 81, 16))
        self.reciever_api_label.setObjectName("reciever_api_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(350, 90, 51, 16))
        self.password_label.setObjectName("password_label")
        self.amount_label = QtWidgets.QLabel(self.centralwidget)
        self.amount_label.setGeometry(QtCore.QRect(100, 90, 49, 16))
        self.amount_label.setObjectName("amount_label")
        self.amount_field = QtWidgets.QLineEdit(self.centralwidget)
        self.amount_field.setGeometry(QtCore.QRect(20, 110, 201, 22))
        self.amount_field.setObjectName("amount_field")
        self.pay_pass_field = QtWidgets.QLineEdit(self.centralwidget)
        self.pay_pass_field.setGeometry(QtCore.QRect(260, 110, 231, 22))
        self.pay_pass_field.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.pay_pass_field.setObjectName("password_field")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(200, 170, 75, 24))
        self.send_button.setObjectName("send_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(410, 170, 75, 24))
        self.save_button.setObjectName("save_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 211, 471, 171))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.your_api_label.setText(_translate("MainWindow", "Your API"))
        self.reciever_api_label.setText(_translate("MainWindow", "Reciever\'s API"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.amount_label.setText(_translate("MainWindow", "Amount"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.save_button.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
